[package]
name = "patina"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "patina"
path = "src/lib.rs"

[[bin]]
name = "patina"
path = "src/main.rs"